### ISSUE TITLE
Support for Basic HTML Drupal webform element

### ISSUE THREAD

**Issue by tonihoo** [oikeuttaelaimille/gatsby-drupal-webform#61]
It would be nice to have support for all Drupal webform elements. At least `Basic HTML` markup element seems to not function at the moment.

Anyhow, great work, thanks!

**Comment by hyrsky** [comment]
PRs are welcome 😅

If I remember correctly Webform has multiple ways to inject html markup. You should check if `processed_text` element will suit your needs. That is implemented.

**Comment by tonihoo** [comment]
Thanks, I'll take a look!

**Comment by tonihoo** [comment]
Yes indeed, Advanced HTML appears to work. I'll use that instead of Basic HTML. 👍
